# Generated by Django 3.0.2 on 2020-07-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], default='MONDAY', max_length=9)),
                ('first', models.CharField(default='', max_length=20)),
                ('second', models.CharField(default='', max_length=20)),
                ('third', models.CharField(default='', max_length=20)),
                ('fourth', models.CharField(default='', max_length=20)),
                ('fifth', models.CharField(default='', max_length=20)),
                ('sixth', models.CharField(default='', max_length=20)),
                ('seventh', models.CharField(default='', max_length=20)),
                ('eighth', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Days',
            },
        ),
    ]
